FROM python

RUN pip install \
    flask \
    flask_api \
    psycopg2 \
    requests \
    pyjwt[crypto]

COPY srv_payment/ /app/
COPY common/ /app/common/

WORKDIR /app

CMD [ "python3", "/app/srv_payment.py" ]
