name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO build, publish to docker hub, deploy to k8s

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      # - name: Login to dockerhub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.HUB_LOGIN }}
      #     password: ${{ secrets.HUB_PASSWD }}

      # - name: Push images
      #   run: docker compose push

      - name: Deploy
        run: |
          kubectl config set-cluster xx_cluster --server="${{ secrets.YDX_ADDR }}" --insecure-skip-tls-verify=true
          kubectl config set-credentials "{{ secrets.YDX_LOGIN }}" --token="${{ secrets.YDX_TOKEN }}"
          kubectl config set-context default --cluster=xx_cluster --user="{{ secrets.YDX_LOGIN }}"
          kubectl config use-context default
          helm delete trash3 || true
          helm install trash3 ./myhelm2/
          sleep 60

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v2/postman/collection.json
          environment: v2/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 5
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"